# Generated by Django 4.0.3 on 2022-04-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitems',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
