# Generated by Django 4.0.3 on 2022-04-12 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_alter_listitems_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listitems',
            options={'ordering': ['-id']},
        ),
    ]
