# Generated by Django 4.0.3 on 2022-04-12 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_alter_listitems_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'ordering': ['-id']},
        ),
    ]
