# Generated by Django 4.0.3 on 2022-04-14 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_alter_checklist_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitems',
            name='completed',
        ),
    ]
