# Generated by Django 4.0.3 on 2022-04-05 17:58

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_album_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, default='default_thumbnail', force_format='JPEG', keep_meta=True, quality=75, size=[350, 250], upload_to='thumbnails'),
        ),
    ]
