# Generated by Django 4.0.3 on 2022-04-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_album_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='likes',
        ),
        migrations.AlterField(
            model_name='album',
            name='thumbnail',
            field=models.ImageField(default='default_thumbnail.jpg', upload_to='thumbnails'),
        ),
    ]
