# Generated by Django 4.0.3 on 2022-04-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_picture_likes_alter_album_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
