# Generated by Django 4.0.3 on 2022-04-10 22:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_album_options_alter_picture_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
