# Generated by Django 4.0.3 on 2022-04-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_album_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='thumbnail',
            field=models.ImageField(default='default_thumbnail.jpg', upload_to='thumbnails'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='photo',
            field=models.ImageField(upload_to='album_pictures'),
        ),
    ]
