# Generated by Django 4.0.3 on 2022-04-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_profile_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.TextField(blank=True, default='No biography yet', max_length=200, null=True),
        ),
    ]
